package cleardev

import "time"

// WorkflowDiagnosis is a read-only explanation, never a grant to retry. Facts
// are sampled separately from recovery admission and must not replace its gates.
type WorkflowDiagnosis struct {
	Phase             string                   `json:"phase"`
	FactSummarySHA256 string                   `json:"factSummarySha256,omitempty"`
	ObservedAt        time.Time                `json:"observedAt"`
	Current           bool                     `json:"current"`
	ReadError         string                   `json:"readError,omitempty"`
	NextOwner         TrustedOwner             `json:"nextOwner"`
	Issues            []WorkflowDiagnosisIssue `json:"issues"`
}

// WorkflowDiagnosisIssue distinguishes a current stop from a previous round's
// failed check. A preceding failure is context, not an extra recovery target.
type WorkflowDiagnosisIssue struct {
	ID           string                      `json:"id"`
	ReasonCode   string                      `json:"reasonCode"`
	Category     string                      `json:"category"`
	Relationship string                      `json:"relationship"`
	SubjectType  string                      `json:"subjectType,omitempty"`
	SubjectID    string                      `json:"subjectId,omitempty"`
	Role         string                      `json:"role,omitempty"`
	AOSessionID  string                      `json:"aoSessionId,omitempty"`
	Summary      string                      `json:"summary,omitempty"`
	Evidence     []WorkflowDiagnosisEvidence `json:"evidence"`
}

// WorkflowDiagnosisEvidence is display-only, bounded and drawn from an existing
// public fact. No credentials, native conversation IDs or prompts are added.
type WorkflowDiagnosisEvidence struct {
	Kind       string     `json:"kind"`
	FactID     string     `json:"factId,omitempty"`
	Value      string     `json:"value"`
	RecordedAt *time.Time `json:"recordedAt,omitempty"`
	Truncated  bool       `json:"truncated,omitempty"`
}

// WorkflowBlockerCategory provides operator guidance, not failure eligibility.
// Known codes are explicit; an unrecognized future error stays UNKNOWN instead of becoming
// an infrastructure error that the UI recommends blindly retrying.
func WorkflowBlockerCategory(reason string) string {
	for category, reasons := range workflowBlockerCategories {
		for _, code := range reasons {
			if code == reason {
				return category
			}
		}
	}
	return "UNKNOWN"
}

var workflowBlockerCategories = map[string][]string{
	"AUTH":              {"LOGIN_REQUIRED", "AUTHENTICATION_REQUIRED"},
	"TOOL":              {"EXECUTION_TOOL_NOT_INSTALLED", "EXECUTION_TOOL_CONFIG_INVALID", "DRIVER_INCOMPATIBLE", "MODEL_NOT_AVAILABLE", "MODEL_UNAVAILABLE", "EXECUTION_CHOICE_CHANGED"},
	"PROVIDER":          {"PROVIDER_UNAVAILABLE", "PROVIDER_FAILURE", "PRODUCT_STEWARD_UNAVAILABLE", "STEWARD_UNAVAILABLE", "PLANNER_UNAVAILABLE", "BUILDER_UNAVAILABLE", "REVIEWER_UNAVAILABLE", "REQUIREMENT_FINAL_REVIEWER_UNAVAILABLE"},
	"QUOTA":             {"QUOTA_EXHAUSTED"},
	"RATE_LIMIT":        {"RATE_LIMITED", "RETRY_NOT_DUE"},
	"OBSERVING":         {"OBSERVATION_TIMEOUT", "OBSERVATION_TIMED_OUT", "PRODUCT_STEWARD_TIMEOUT", "STEWARD_TIMEOUT", "PLANNER_TIMEOUT", "BUILDER_TIMEOUT", "REVIEW_TIMEOUT", "REVIEWER_TIMEOUT", "REQUIREMENT_FINAL_REVIEW_TIMEOUT"},
	"UNKNOWN_DELIVERY":  {"DELIVERY_UNKNOWN", "DELIVERY_UNCONFIRMED", "RESULT_NOT_SETTLED", "RECOVERY_RESULT_UNKNOWN", "ORIGINAL_SESSION_RESTORE_UNCONFIRMED", "REVIEWER_CREATION_UNCONFIRMED", "RECOVERY_UNCONFIRMED"},
	"SESSION":           {"BUILDER_SPAWN_FAILED", "SESSION_LOST", "TURN_INTERRUPTED", "RECOVERY_SESSION_UNAVAILABLE", "RECOVERY_NATIVE_IDENTITY_MISSING", "BUILDER_STEP_UNAVAILABLE", "STEWARD_SPAWN_FAILED", "PLANNER_SPAWN_FAILED", "REVIEWER_SPAWN_FAILED", "REVIEW_BRANCH_UNAVAILABLE", "REQUIREMENT_FINAL_REVIEW_BRANCH_UNAVAILABLE"},
	"FORMAT":            {"RESULT_INVALID", "RESULT_PARSE_FAILED", "BUILDER_RESULT_INVALID", "STEWARD_RESULT_INVALID", "PLANNER_RESULT_INVALID", "REVIEW_RESULT_INVALID", "REVIEWER_RESULT_INVALID", "PRODUCT_DISCOVERY_INVALID", "SPECIALIST_RESULT_INVALID", "REQUIREMENT_FINAL_REVIEW_INVALID", "REQUIREMENT_FINAL_REVIEW_RESULT_INVALID"},
	"INPUT":             {"COMPILATION_NEEDS_HUMAN", "PLAN_REVIEW_BLOCKED", "BUILDER_BLOCKED", "BUILDER_NEEDS_HUMAN", "REVIEW_BLOCKED", "REVIEW_NEEDS_HUMAN", "PRODUCT_CLARIFICATION_REQUIRED", "AWAITING_CLARIFICATION", "AWAITING_INPUT"},
	"HUMAN":             {"HUMAN_DECISION_REQUIRED", "AWAITING_CONFIRMATION", "AWAITING_DECISION", "REJECTED_BY_DESKTOP_HUMAN", "PENDING_DECISION", "HUMAN_AUTHORITY_UNAVAILABLE"},
	"BUDGET":            {"BUILDER_BUDGET_EXHAUSTED", "REVIEWER_BUDGET_EXHAUSTED", "EXCEPTION_BUDGET_EXHAUSTED", "MESSAGE_BUDGET_EXHAUSTED", "ROLE_BUDGET_LIMIT", "PLANNING_REPLAN_LIMIT_REACHED", "PRODUCT_DISCUSSION_LIMIT_REACHED", "FINAL_REVIEW_REWORK_LIMIT", "MAIL_ATTEMPTS_EXHAUSTED", "MAIL_EXTRA_ATTEMPT_EXHAUSTED", "REWORK_LIMIT_REACHED"},
	"EVIDENCE":          {"MESSAGE_BUDGET_UNKNOWN", "MESSAGE_BUDGET_BINDING_INVALID", "MESSAGE_BUDGET_STORE_UNAVAILABLE", "ATTEMPT_STORE_UNAVAILABLE", "CURRENT_BINDINGS_CHANGED", "DEPENDENCY_EVIDENCE_INCOMPLETE", "PLANNER_VALIDATION_REQUIRED", "GENERATED_PROOF_MISSING", "GENERATED_PROOF_MISMATCH", "RECOVERY_NOT_TRIGGERED", "RECOVERY_NEEDS_HUMAN", "RECOVERY_FAILED", "EXECUTION_RECOVERY", "TASK_BLOCKED", "EXECUTION_BLOCKED", "INTEGRATION_FAILED", "UNKNOWN", "FAILED", "BLOCKED", "NEEDS_HUMAN", "PREFLIGHT_OR_DELIVERY_REQUIRED"},
	"SOURCE":            {"PRODUCT_BASELINE_CHANGED", "PRODUCT_PLAN_SUPERSEDED", "PLANNING_NOT_CURRENT", "PLANNING_SOURCE_CHANGED", "EXECUTION_NOT_CURRENT", "EXECUTION_TASK_SET_CHANGED", "RECOVERY_NOT_CURRENT", "RECOVERY_CANDIDATE_CHANGED", "MAIL_FINAL_CANDIDATE_CHANGED", "RESULT_SOURCE_CHANGED", "RESULT_BINDING_CHANGED", "CANDIDATE_NOT_DESCENDANT", "SCOPE_STALE_BINDING", "SPECIALIST_BINDING_CHANGED"},
	"WORKTREE":          {"PRODUCT_STEWARD_WORKSPACE_CHANGED", "PRODUCT_PLANNER_WORKSPACE_CHANGED", "BUILDER_WORKTREE_DIRTY", "REVIEW_WORKTREE_INVALID", "CANDIDATE_INVALID", "WORKSPACE_DIRTY", "GIT_UNAVAILABLE", "BASELINE_UNAVAILABLE"},
	"SCOPE":             {"SCOPE_PATH_NOT_LISTED", "SCOPE_PATH_FORBIDDEN", "SCOPE_PATH_CONCURRENT", "SCOPE_REQUEST_INVALID", "SCOPE_DECISION_INVALID", "SCOPE_DUPLICATE_REQUEST", "SCOPE_CHECK_FAILED", "SHARED_PATH_REQUIRES_APPROVAL", "SPECIALIST_REQUIRED"},
	"CHECK_FAILURE":     {"CHECK_FAILED", "CHECK_TIMEOUT", "REVIEW_REWORK", "REWORK_REQUIRED", "BASELINE_TEST_FAILED", "BASELINE_HEALTH_FAILED"},
	"CHECK_ENVIRONMENT": {"CHECKER_UNAVAILABLE", "CHECK_ENVIRONMENT_UNAVAILABLE", "CHECK_ENVIRONMENT_INVALID", "INTEGRATION_CHECKER_UNAVAILABLE"},
	"RESOURCE":          {"CHECK_CAPACITY_EXCEEDED", "STAGE_TRIAL_CAPACITY", "RESULT_DATA_CAPACITY", "CAPACITY_EXCEEDED", "RESOURCE_CLEANUP_UNCONFIRMED"},
	"INTEGRATION":       {"COMPOSITION_CONFLICT", "COMPOSITION_INVALID", "INTEGRATION_CONFLICT", "INTEGRATION_CHECK_FAILED"},
	"TRIAL":             {"STAGE_TRIAL_REQUIRED", "STAGE_TRIAL_UNAVAILABLE", "STAGE_TRIAL_UNSUPPORTED", "STAGE_TRIAL_FAILED", "REQUIREMENT_FINAL_REVIEW_BLOCKED", "REQUIREMENT_FINAL_REVIEW_NEEDS_HUMAN", "REQUIREMENT_FINAL_REVIEW_REWORK"},
	"PREREQUISITE":      {"PRODUCT_PREVIOUS_STAGE_REQUIRED", "PRODUCT_PREVIOUS_STAGE_BASELINE_REQUIRED", "COMPLEX_PLAN_REQUIRED", "COMPLEX_EXECUTION_PLAN_NOT_READY", "PROJECT_EXECUTION_ADMISSION_REQUIRED", "PROJECT_EXECUTION_NOT_AVAILABLE", "RESULT_NOT_COMPLETED", "RESULT_NOT_READY", "WAITING_PREDECESSOR", "AWAITING_EXECUTION"},
	"DATA":              {"RESULT_START_FAILED", "RESULT_DATA_PREPARATION_REQUIRED", "RESULT_DATA_BASELINE_CHANGED", "RESULT_DATA_MIGRATION_FAILED", "RESULT_DATA_INVALID", "RESULT_HEALTH_FAILED"},
	"STOPPED":           {"REQUIREMENT_CANCELLED", "PRODUCT_CANCELLED", "CANCELLED", "PAUSED", "DIRECTION_CHANGE_STOPPED", "RECOVERY_DIRECTION_STOP", "COMPLEX_EXECUTION_STOPPED"},
	"CAPABILITY":        {"PROJECT_RUNTIME_UNSUPPORTED", "NEEDS_CAPABILITY", "PARALLEL_NOT_AVAILABLE", "ONE_BUILDER_REQUIRED", "QUICK_NOT_SINGLE_COMPLETED_TASK", "QUICK_PATHS_NOT_SUBSET", "QUICK_FILE_LIMIT_EXCEEDED", "QUICK_UNKNOWN_IDS", "QUICK_SHARED_OR_GENERATED_PATHS", "QUICK_SENSITIVE_PATH", "QUICK_CHECKS_NOT_FROM_PLAN", "QUICK_INTEGRATION_BASE_MISMATCH", "QUICK_TASK_SET_CHANGED", "QUICK_UNSAFE", "MAIL_EXECUTION_POLICY_REQUIRED"},
	"REGISTERED":        {"CONTINUATION_REGISTERED", "BUILDER_RECHECK_REGISTERED"},
}
